#!/usr/bin/python
# -*- coding:utf-8 -*-

# 작성자 : 한석현
import sys
import os
import commands

def check():
	for i in range(2,10):
		for j in range(1,10):
			print i*j
		print " "

if __name__ == '__main__':
	check()
